name: Production Build

on:
  push:
    branches:
      - main 
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - uses: actions/checkout@v2
        with:
          path: main

      - name: Install poppler
        run: sudo apt-get install poppler-utils

      - name: Install pip
        working-directory: main/scraper
        run: python -m pip install --upgrade pip

      - name: Install bs
        working-directory: main/scraper
        run: pip install bs4

      - name: Install requests
        working-directory: main/scraper
        run: pip install requests

      - name: Install dateutil
        working-directory: main/scraper
        run: pip install python-dateutil

      - name: Run scaper
        working-directory: main/scraper
        run: python scraper.py

      - name: Copy output
        working-directory: main
        run: cp scraper/bills.json app/src

      - name: Yarn Install
        working-directory: main/app
        run: |
          yarn install

      - name: Production Build
        working-directory: main/app
        run: |
          CI=false yarn build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: 'capitoltracker.mountainstatespotlight.org'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: "main/app/build"

      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: bill-tracker
          status: SUCCESS
          color: good

      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: bill-tracker
          status: FAILED
          color: danger
