name: Production Build
on:
  pull_request:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: app
jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Yarn Install
      run: |
        yarn install
    - name: Production Build
      run: |
        CI=false yarn build
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@v0.5.1

      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: 'wvlegislaturetracker.org'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: "build"
