name: Build Site

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - uses: actions/checkout@v2
        with:
          path: main

      - name: Retrieve from s3
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          dest: 'main/app/src/bills.json'
          source: 's3://capitoltracker.mountainstatespotlight.org/output/bills.json'

      - name: Yarn Install
        working-directory: main/app
        run: |
          yarn install

      - name: Production Build
        working-directory: main/app
        run: |
          CI=false yarn build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: 'capitoltracker.mountainstatespotlight.org'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: "main/app/build"